version: 0.2

phases:
  install: 
    runtime-versions:
      nodejs: 10.24.1  # Use a specific version that's supported
    commands:
      - echo "Installing dependencies"
      - npm install  # Removed the -f flag
      - echo "Dependencies have been installed"

  build:
    commands:
      - echo "Building the project"
      - echo "Storing Build Artifact to the Location"

artifacts:
  files:
    - '**/*'  # Include all files; adjust this if you want to be more specific
